---
- hosts: localhost
  connection: local
  
  tasks:
    - name: Ensure bin directory exists
      file:
        path: $HOME/bin
        state: directory
        mode: u+rwx,g+rx,o+rx

    - name: Ensure bin directory in path
      lineinfile:
        dest: $HOME/.zshrc
        line: 'export PATH=$PATH:$HOME/bin'
        create: yes

    - name: Loop over the directories and copy the scripts to the bin directory
      copy:
        src: "{{ item }}"
        dest: $HOME/bin
        mode: u+rwx,g+rx,o+rx
      with_fileglob:
        - scripts/*.sh
        - scripts/*.py
      register: copied_files

    - name: Rename files to remove extension
      command: cp "{{ item.dest }}" "{{ item.dest | regex_replace('\.sh$', '') | regex_replace('\.py$', '')}}"
      with_items: "{{ copied_files.results }}"
      when: item.changed

    - name: Get playbook directory
      debug:
        var: playbook_dir

    - name: Ensure repo is checkout via cron once a day
      cron:
        name: "Checkout tools repo"
        minute: 0
        hour: 0
        job: "cd {{ playbook_dir }} && git pull"